### ISSUE TITLE
Implement local.FilesystemStore

### ISSUE THREAD

**Issue by GeorgeMac** [flipt-io/cup#9]
This issues tracks the work required to build a local `FilesystemStore` for the `pkg/api` package.

This source is primarily useful for local evaluation / development experience.
This storage implementation works directly on the underlying target filesystem.
There are no proposals made during an update, just direct and immediate effect change.

The implementation should be super straight-forward and we can simply just pass the path to the location on the actual filesystem.

The store should be configurable such that, in theory, multiple directories could be named in configuration.

```yaml
sources:
  flipt:
    type: local
    local:
      path: "/projects/flipt"
  cup:
    type: local
    local:
      path: "/projects/cup"
```

Ultimately, these manifest as API Server sources:

```
/apis/flipt/...

/apis/cup/...
```
